package uk.co.palmr.gennaker.codec.sbe;

import uk.co.real_logic.sbe.generation.java.JavaOutputManager;

import javax.annotation.processing.FilerException;
import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.TypeElement;
import java.io.IOException;
import java.io.Writer;

/**
 * Adapts SBE's JavaOutputManager to write generated sources through the
 * annotation processor's Filer so that javac picks them up for compilation
 * in subsequent processing rounds.
 *
 * <p>When the Filer reports that a file was already created in this round
 * (e.g. shared header types generated by a second {@code @Topic} interface
 * in the same package), we fall back to writing via the filesystem path that
 * the parent {@code JavaOutputManager} manages. The file is already registered
 * with javac from the first creation, so it will still be compiled.
 */
public class AnnotationFilerOutputManager extends JavaOutputManager {
    private final String packageName;
    private final ProcessingEnvironment processingEnv;
    private final TypeElement interfaceElement;

    public AnnotationFilerOutputManager(final String baseDirName,
                                        final String packageName,
                                        final ProcessingEnvironment processingEnv,
                                        final TypeElement interfaceElement) {
        super(baseDirName, packageName);
        this.packageName = packageName;
        this.processingEnv = processingEnv;
        this.interfaceElement = interfaceElement;
    }

    @Override
    public Writer createOutput(final String name) throws IOException {
        try {
            final var f = processingEnv.getFiler().createSourceFile(packageName + "." + name, interfaceElement);
            return f.openWriter();
        } catch (final FilerException alreadyCreated) {
            return super.createOutput(name);
        }
    }
}
