[versions]
junitVersion = "5.13.1"
junitPlatformVersion = "1.13.1"
aeronVersion = "1.48.1"
sbeVersion = "1.35.3"
agronaVersion = "2.2.2"
slf4jVersion = "2.0.17"
logbackVersion = "1.5.18"
compileTestingVersion = "0.21.0"

[libraries]
aeron = { group = "io.aeron", name = "aeron-all", version.ref = "aeronVersion" }
agrona = { group = "org.agrona", name = "agrona", version.ref = "agronaVersion" }
sbe = { group = "uk.co.real-logic", name = "sbe-tool", version.ref = "sbeVersion" }
jupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junitVersion" }
jupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junitVersion" }
jupiterPlatform = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junitPlatformVersion" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4jVersion" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logbackVersion" }
compileTesting = { group = "com.google.testing.compile", name = "compile-testing", version.ref = "compileTestingVersion" }


[bundles]
testing = [ "jupiterApi", "jupiterEngine", "jupiterPlatform"]
