package uk.co.palmr.gennaker;

/// Runtime entry point. Wraps a [Transport] and hands out publisher proxies
/// and subscriber registrations for `@Topic`-annotated interfaces whose
/// proxies were generated by the annotation processor.
///
/// ```java
/// var gennaker = new Gennaker(new AeronTransport());
/// Ping pub = gennaker.publisher(Ping.class);
/// gennaker.subscribe(Ping.class, new MyPingHandler());
/// ```
public final class Gennaker {
    private static final System.Logger LOG = System.getLogger(Gennaker.class.getName());

    private final Transport transport;

    /// Creates a Gennaker instance bound to the given transport. The transport
    /// is used for all publishers and subscriptions created from this instance.
    ///
    /// @param transport the transport to publish on and subscribe through
    public Gennaker(final Transport transport) {
        this.transport = transport;
    }

    /// Registers a handler for inbound messages on a topic. The handler is
    /// invoked with decoded arguments via the generated subscriber proxy.
    ///
    /// @param topicClass          the `@Topic`-annotated interface
    /// @param topicImplementation user code implementing that interface
    /// @param <T>                 the topic interface type
    /// @param <I>                 a subtype of `T` implementing the topic
    public <T, I extends T> void subscribe(final Class<T> topicClass, final I topicImplementation) {
        LOG.log(System.Logger.Level.INFO, "subscribed {0} -> {1}",
                topicClass.getName(), topicImplementation.getClass().getName());
        transport.subscribe(topicClass, ClassHunter.getSubscriberProxy(topicClass, topicImplementation));
    }

    /// Returns a publisher proxy implementing the topic interface. Each method
    /// call on the returned object encodes its arguments and offers the
    /// resulting message to the configured transport.
    ///
    /// @param topicClass the `@Topic`-annotated interface
    /// @param <T>        the topic interface type
    /// @return a publisher proxy implementing `topicClass`
    public <T> T publisher(final Class<T> topicClass) {
        LOG.log(System.Logger.Level.INFO, "created publisher for {0}", topicClass.getName());
        return ClassHunter.getPublisherProxy(topicClass, transport);
    }

    /// Releases transport-held resources (Aeron publications, subscriptions,
    /// media driver, etc.). Call once on shutdown.
    public void shutdown() {
        transport.shutdown();
    }
}
